import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const desktopRoot = fileURLToPath(new URL('..', import.meta.url))

describe('desktop data-home chooser', () => {
  it('presents all three data strategies and the comparison dialog', async () => {
    const html = await readFile(`${desktopRoot}/src/data-home.html`, 'utf8')
    expect(html).toContain('data-mode="imported"')
    expect(html).toContain('data-mode="reused"')
    expect(html).toContain('data-mode="fresh"')
    expect(html).toContain('id="detail" class="detail" data-mode="imported"')
    expect(html).toContain('.choice[data-mode="imported"]')
    expect(html).toContain('.detail[data-mode="imported"]')
    expect(html).toContain('class="comparison-table-wrap"')
    expect(html).toContain('thead th[data-mode="imported"]')
    expect(html).toContain('thead th[data-mode="reused"]')
    expect(html).toContain('thead th[data-mode="fresh"]')
    expect(html).toContain('@media (prefers-reduced-motion: reduce)')
    expect(html).not.toContain('reuse-column')
    expect(html).toContain('id="help"')
    expect(html).toContain('id="overlay"')
    expect(html).toContain('id="continue"')
    expect(html).toContain('id="language-trigger"')
    expect(html).toContain('id="language-menu"')
    expect(html).toContain('<strong>DeepSeek Harness</strong>')
    expect(html).toContain('class="language-inline-label"')
    expect(html).toContain('height: 40px; width: 40px;')
    expect(html).toContain('.brand-copy strong { font-size: 18px;')
    expect(html).toContain('data-language="zh"')
    expect(html).toContain('data-language="en"')
    expect(html).not.toContain('<select id="language"')
    expect(html).toContain('导入官方配置（独立环境）')
    expect(html).toContain('padding: 24px 14px')
    expect(html).not.toContain('.choice:first-child { padding-top: 8px; }')
    expect(html).toContain('color-scheme: light dark')
    expect(html).toContain('@media (prefers-color-scheme: dark)')
  })

  it('keeps the chooser sandboxed and sends only bounded selections', async () => {
    const html = await readFile(`${desktopRoot}/src/data-home.html`, 'utf8')
    const preload = await readFile(`${desktopRoot}/src/data-home-preload.ts`, 'utf8')
    expect(html).toContain("default-src 'none'")
    expect(html).not.toContain('<script')
    expect(preload).toContain("type DataHomeMode = 'imported' | 'reused' | 'fresh'")
    expect(preload).toContain("ipcRenderer.send('dsh:data-home:selected', selected)")
    expect(preload).toContain("ipcRenderer.send('dsh:data-home:cancelled')")
    expect(preload).toContain("languageTrigger.addEventListener('click'")
    expect(preload).toContain("option.addEventListener('click'")
    expect(preload).toContain("event.key === 'ArrowDown' || event.key === 'ArrowUp'")
    expect(preload).toContain('detailPanel.dataset.mode = mode')
    expect(preload).toContain('Copy a plugin restore list without Profiles, node_modules, or lockfiles')
    expect(preload).toContain('Every explicit false remains denied')
  })

  it('uses the branded icon before opening the chooser in development', async () => {
    const html = await readFile(`${desktopRoot}/src/data-home.html`, 'utf8')
    const main = await readFile(`${desktopRoot}/src/main.ts`, 'utf8')
    const ready = main.indexOf('await app.whenReady()')
    const dockIcon = main.indexOf('applyDevelopmentDockIcon()', ready)
    const chooser = main.indexOf('await prepareDesktopDshHome(DESKTOP_DATA_HOME)', ready)

    expect(html).toContain('<img src="icon.png" alt="">')
    expect(ready).toBeGreaterThan(-1)
    expect(dockIcon).toBeGreaterThan(ready)
    expect(chooser).toBeGreaterThan(dockIcon)
  })
})
